/**
 * Textos da interface: `[português, inglês]`. `{0}`, `{1}`… são argumentos de `t()`.
 * Uma fonte só para os dois idiomas — chave sem par não passa no teste de paridade.
 */
export const DICT: Record<string, [string, string]> = {
  locale: ["pt-BR", "en-US"],

  // navegação, ferramentas, comum
  "nav.aria": ["seção", "section"],
  "nav.maps": ["Mapas", "Maps"],
  "nav.resources": ["Recursos", "Resources"],
  "tools.lang": ["idioma (PT/EN)", "language (PT/EN)"],
  "tools.theme": ["alternar tema claro/escuro", "toggle light/dark theme"],
  "common.close": ["fechar", "close"],
  "common.loading": ["carregando…", "loading…"],
  "common.yes": ["sim", "yes"],
  "common.no": ["não", "no"],

  // filtros
  "filter.search.label": ["filtrar mapas", "filter maps"],
  "filter.search.ph": ["filtrar por nome, título, modo ou tag…", "filter by name, title, mode or tag…"],
  "filter.mode": ["modo de jogo", "game mode"],
  "filter.mode.all": ["todos os modos", "all modes"],
  "filter.severity": ["gravidade", "severity"],
  "filter.severity.any": ["qualquer situação", "any status"],
  "filter.severity.critical": ["com problema crítico", "with a critical issue"],
  "filter.severity.warn": ["com aviso", "with a warning"],
  "filter.severity.clean": ["sem problemas", "no issues"],
  "filter.rule": ["regra do diagnóstico", "diagnostic rule"],
  "filter.rule.any": ["qualquer regra", "any rule"],
  "filter.tag": ["tag", "tag"],
  "filter.tag.any": ["todas as tags", "all tags"],
  "filter.fav": ["só favoritos", "favorites only"],
  "sort.label": ["ordenação", "sort order"],
  "sort.name": ["nome", "name"],
  "sort.size": ["tamanho do arquivo", "file size"],
  "sort.spawns": ["spawns", "spawns"],
  "sort.area": ["área do mapa", "map area"],
  "sort.problems": ["problemas primeiro", "problems first"],
  "slots.label": ["slots", "slots"],
  "slots.title": [
    "slots do servidor — quantos jogadores o mapa precisa aguentar",
    "server slots — how many players the map must hold",
  ],
  "pick.button": ["escolher pasta…", "choose folder…"],
  "pick.title": ["pasta com os .bsp", "folder with the .bsp files"],
  "compare.button": ["comparar", "compare"],
  "compare.buttonN": ["comparar ({0})", "compare ({0})"],
  "audit.button": ["auditar pasta", "audit folder"],
  "audit.title": [
    "roda o diagnóstico completo em todos os mapas da pasta",
    "runs the full diagnosis on every map in the folder",
  ],

  // galeria e cards
  "gallery.empty": [
    "Nenhum mapa carregado. Clique em <strong>escolher pasta…</strong> e aponte para a pasta <code>maps</code> do cstrike.",
    "No maps loaded. Click <strong>choose folder…</strong> and point to the cstrike <code>maps</code> folder.",
  ],
  "gallery.noMatch": ["Nenhum mapa bate com o filtro.", "No map matches the filter."],
  "card.open": ["abrir detalhes de {0}", "open details of {0}"],
  "card.spawns": ["spawns", "spawns"],
  "card.entities": ["entidades", "entities"],
  "card.file": ["arquivo", "file"],
  "card.compare": ["marcar para comparar", "select to compare"],
  "card.compareAria": ["comparar {0}", "compare {0}"],
  "status.count": ["{0} de {1} mapa(s)", "{0} of {1} map(s)"],
  "status.count.problems": ["{0} de {1} mapa(s) · {2} com aviso", "{0} of {1} map(s) · {2} with warnings"],
  "status.reading": ["lendo {0}…", "reading {0}…"],
  "status.exported": ["exportado para {0}", "exported to {0}"],

  // modos de jogo
  "mode.bomb": ["de_ · bomba", "de_ · bomb"],
  "mode.hostage": ["cs_ · reféns", "cs_ · hostages"],
  "mode.assassination": ["as_ · VIP", "as_ · VIP"],
  "mode.escape": ["es_ · fuga", "es_ · escape"],
  "mode.zombie": ["zombie plague", "zombie plague"],
  "mode.deathmatch": ["deathmatch", "deathmatch"],
  "mode.unknown": ["indefinido", "undefined"],

  // etiquetas curtas das regras (card, filtro, comparação)
  "rule.de-sem-bomb-target": ["de_ sem alvo de bomba", "de_ without bomb target"],
  "rule.cs-sem-refem": ["cs_ sem refém", "cs_ without hostage"],
  "rule.cs-sem-resgate": ["refém sem zona de resgate", "hostage without rescue zone"],
  "rule.as-incompleto": ["as_ incompleto", "as_ incomplete"],
  "rule.prefixo-divergente": ["prefixo divergente", "prefix mismatch"],
  "rule.sem-spawn": ["sem spawn", "no spawn"],
  "rule.spawn-de-um-time-so": ["spawn de um time só", "one team's spawns only"],
  "rule.poucos-spawns": ["poucos spawns", "too few spawns"],
  "rule.fullbright": ["fullbright", "fullbright"],
  "rule.sem-buyzone": ["sem buyzone", "no buyzone"],
  "rule.mapa-pesado": ["mapa pesado", "heavy map"],
  "rule.wad-nao-declarado": ["WAD não declarado", "WAD not declared"],
  "rule.spawn-em-solido": ["spawn em parede", "spawn inside a wall"],
  "rule.sem-vis": ["sem VIS (leak?)", "no VIS (leak?)"],
  "rule.limite-motor": ["limite do motor", "engine limit"],
  "rule.wad-nao-encontrado": ["WAD não encontrado", "WAD not found"],
  "rule.textura-ausente": ["textura ausente", "missing texture"],
  "rule.recurso-ausente": ["recurso ausente", "missing resource"],
  "rule.erro-leitura": ["erro de leitura", "read error"],

  // detalhe
  "detail.aria": ["detalhes do mapa", "map details"],
  "detail.reading": ["lendo {0}…", "reading {0}…"],
  "detail.exportSvg": ["exportar planta (SVG)", "export floor plan (SVG)"],
  "detail.polygons": ["{0} polígonos desenhados", "{0} polygons drawn"],
  "detail.diagnosis": ["Diagnóstico", "Diagnosis"],
  "detail.noIssues": ["Nenhum problema conhecido", "No known issues"],
  "detail.geometry": ["Geometria", "Geometry"],
  "detail.dimensions": ["dimensões", "dimensions"],
  "detail.units": ["un", "units"],
  "detail.faces": ["faces", "faces"],
  "detail.vertices": ["vértices", "vertices"],
  "detail.models": ["modelos (brush entities)", "models (brush entities)"],
  "detail.file": ["arquivo", "file"],
  "detail.textures": ["Texturas", "Textures"],
  "detail.texTotal": ["total", "total"],
  "detail.texEmbedded": ["embutidas no BSP", "embedded in the BSP"],
  "detail.sky": ["céu", "sky"],
  "detail.wads": ["WADs declarados", "declared WADs"],
  "detail.none": ["nenhum", "none"],
  "detail.topEntities": ["Entidades mais usadas", "Most used entities"],
  "detail.lumps": ["O que pesa no arquivo", "What weighs in the file"],
  "detail.texUsed": ["{0} textura(s) usadas", "{0} texture(s) used"],

  // visões e viewer
  "view.plan": ["Planta", "Plan"],
  "view.3d": ["3D", "3D"],
  "view.tex": ["3D + texturas", "3D + textures"],
  "viewer.loading": ["montando cena 3D…", "building 3D scene…"],
  "viewer.lightmaps": ["luz (lightmaps)", "lighting (lightmaps)"],
  "viewer.pvs": ["corte por PVS", "PVS culling"],
  "viewer.alpha": ["texturas transparentes", "transparent textures"],
  "viewer.fps": ["primeira pessoa", "first person"],
  "viewer.fpsExit": ["sair (Esc)", "exit (Esc)"],
  "viewer.fullscreen": ["tela cheia", "fullscreen"],
  "viewer.fullscreenExit": ["sair da tela cheia", "exit fullscreen"],
  "viewer.orbitHint": ["arraste para girar · scroll para zoom", "drag to rotate · scroll to zoom"],
  "viewer.fpsHint": ["WASD mover · mouse olhar · Space/Ctrl sobe/desce", "WASD move · mouse look · Space/Ctrl up/down"],
  "viewer.tris": ["{0} / {1} triângulos", "{0} / {1} triangles"],
  "viewer.leaf": ["folha {0}", "leaf {0}"],
  "legend.ct": ["spawn CT", "CT spawn"],
  "legend.t": ["spawn T", "T spawn"],
  "legend.height": ["altura (baixo → alto)", "height (low → high)"],

  // notas, tags, favoritos
  "note.title": ["Notas e tags", "Notes and tags"],
  "note.favorite": ["favorito", "favorite"],
  "note.tagPlaceholder": ["nova tag…", "new tag…"],
  "note.addTag": ["adicionar", "add"],
  "note.removeTag": ["remover a tag {0}", "remove tag {0}"],
  "note.note": ["nota sobre o mapa", "note about the map"],
  "note.notePlaceholder": ["Anotações sobre o mapa (ficam salvas neste computador)…", "Notes about the map (saved on this computer)…"],

  // recursos / FastDL
  "res.title": ["Recursos necessários (FastDL)", "Required resources (FastDL)"],
  "res.summary": [
    "O jogador baixa {0} arquivo(s), {1}. Ausentes no disco: {2}.",
    "Players download {0} file(s), {1}. Missing on disk: {2}.",
  ],
  "res.export": ["exportar lista de FastDL (.txt)", "export FastDL list (.txt)"],
  "res.state.download": ["baixar", "download"],
  "res.state.shared": ["do jogo base", "base game"],
  "res.state.missing": ["ausente", "missing"],
  "res.kind.mapa": ["mapa", "map"],
  "res.kind.res": [".res", ".res"],
  "res.kind.txt": ["descrição", "description"],
  "res.kind.overview": ["overview", "overview"],
  "res.kind.wad": ["WAD", "WAD"],
  "res.kind.sky": ["céu", "sky"],
  "res.kind.model": ["modelo", "model"],
  "res.kind.sprite": ["sprite", "sprite"],
  "res.kind.sound": ["som", "sound"],
  "res.kind.extra": ["extra", "extra"],

  // entidades
  "ent.title": ["Entidades", "Entities"],
  "ent.open": ["Ver as {0} entidades (clique para localizar no 3D)", "Browse the {0} entities (click to locate in 3D)"],
  "ent.search": ["buscar por classe, nome ou valor…", "search by class, name or value…"],
  "ent.count": ["{0} de {1}", "{0} of {1}"],
  "ent.go": ["ver no 3D", "show in 3D"],
  "ent.keys": ["{0} chaves", "{0} keys"],
  "ent.more": ["… e mais {0}. Refine a busca.", "… and {0} more. Narrow the search."],

  // radar
  "radar.title": ["Radar (overview)", "Radar (overview)"],
  "radar.desc": [
    "Vista de cima em tons de verde, no estilo do radar do CS. Exporta overviews/<mapa>.bmp, .png e .txt.",
    "Top-down view in shades of green, CS radar style. Exports overviews/<map>.bmp, .png and .txt.",
  ],
  "radar.preview": ["gerar prévia", "generate preview"],
  "radar.export": ["exportar para overviews/…", "export to overviews/…"],
  "radar.alt": ["radar de {0}", "radar of {0}"],
  "radar.pickDir": ["pasta do mod (onde fica overviews/)", "mod folder (where overviews/ lives)"],
  "radar.done": ["{0} arquivo(s) gravado(s) em {1}/overviews", "{0} file(s) written to {1}/overviews"],

  // comparação
  "cmp.title": ["Comparar {0} × {1}", "Compare {0} × {1}"],
  "cmp.mode": ["modo", "mode"],
  "cmp.version": ["versão do BSP", "BSP version"],
  "cmp.spawns": ["spawns", "spawns"],
  "cmp.entities": ["entidades", "entities"],
  "cmp.fixed": ["Problemas que sumiram (em B)", "Issues gone (in B)"],
  "cmp.added": ["Problemas novos (em B)", "New issues (in B)"],
  "cmp.lumps": ["Lumps que mudaram de tamanho", "Lumps that changed size"],
  "cmp.ents": ["Entidades que mudaram de quantidade", "Entities whose count changed"],
  "cmp.noDiff": ["Sem diferenças.", "No differences."],
  "cmp.texOnly": ["Texturas só em {0}", "Textures only in {0}"],
  "cmp.wadOnly": ["WADs só em {0}", "WADs only in {0}"],

  // auditoria e relatório
  "audit.title2": ["Auditoria da pasta", "Folder audit"],
  "audit.running": ["Rodando o diagnóstico completo em todos os mapas…", "Running the full diagnosis on every map…"],
  "audit.needFolder": ["Escolha uma pasta de mapas antes de auditar.", "Choose a maps folder before auditing."],
  "audit.maps": ["mapas", "maps"],
  "audit.critical": ["críticos", "critical"],
  "audit.warn": ["com aviso", "with warnings"],
  "audit.clean": ["limpos", "clean"],
  "audit.errors": ["ilegíveis", "unreadable"],
  "audit.dups": ["grupos duplicados", "duplicate groups"],
  "audit.exportMd": ["exportar Markdown", "export Markdown"],
  "audit.exportCsv": ["exportar CSV", "export CSV"],
  "audit.exportHtml": ["exportar HTML", "export HTML"],
  "report.title": ["Auditoria do acervo de mapas", "Map collection audit"],
  "report.folder": ["Pasta", "Folder"],
  "report.slots": ["Slots", "Slots"],
  "report.summary": [
    "{0} mapa(s): {1} crítico(s), {2} com aviso, {3} limpo(s), {4} ilegível(is)",
    "{0} map(s): {1} critical, {2} with warnings, {3} clean, {4} unreadable",
  ],
  "report.duplicates": ["Arquivos duplicados", "Duplicate files"],
  "report.col.map": ["Mapa", "Map"],
  "report.col.mode": ["Modo", "Mode"],
  "report.col.size": ["Tamanho", "Size"],
  "report.col.spawns": ["Spawns CT/T", "Spawns CT/T"],
  "report.col.severity": ["Gravidade", "Severity"],
  "report.col.rule": ["Regra", "Rule"],
  "report.col.finding": ["Achado", "Finding"],
  "report.col.findings": ["Achados", "Findings"],
};
